### ISSUE TITLE
Low traffic or publish-only connections are closed with "too many missed heartbeats"

### ISSUE THREAD

**Issue by rajmaniar** [achilleasa/dart_amqp#106]
When we have a connection to rabbit with very low consumer traffic or a connection with not consumers (only used for publishing) we get an occasion close with the message `too many missed heartbeats`

I'll add more details to this ticket as I investigate this a bit more so it's a placeholder for now.

**Comment by rajmaniar** [comment]
We're also seeing the client generated exception: `Server did not respond to heartbeats for 30s`

**Comment by achilleasa** [comment]
According to https://www.rabbitmq.com/heartbeats.html#heartbeats-interval any incoming message (heartbeat or not) from the broker can be treated as a heartbeat. This is the approach that this client also implements.

In addition, the client sets up a timer (interval = half the heartbeat timeout) which is used to send out periodic heartbeat frames to the broker to prevent exactly the scenario you describe...

To help me diagnose the issue, can you add some logging statements in [writeHeartbeat](https://github.com/achilleasa/dart_amqp/blob/master/lib/src/client/impl/channel_impl.dart#L62-L78) (specifically, L64 before the return, L71 before returning and L76 inside the catch block) and let me know if the client fails to write the heartbeat frame?

**Comment by achilleasa** [comment]
The 3rd option (counting heartbeats in flight and disconnecting once a threshold is exceeded) sounds like the more robust approach to me. I will propose a PR to implement this mechanism.

**Comment by achilleasa** [comment]
@mchandler-plato  Can you please check if #111 rectifies the issues you are having?

**Comment by Boris-Plato** [comment]
@achilleasa We work together with @mchandler-plato, and he is on vacation now. I have a branch in my forked repo where I skip every second sent heartbeat, which helps catch broken heartbeat state quite fast. I just tried your PR with this scenario, and it looks to be fixed - I do not see "broken heartbeats" restarts anymore. So 1st check is good. But the main check will be when we deeply your changes to prod, I'll discuss it with the team soon. Right now, we use in prod our own "2x check timer duration" fix, which also helps for my test scenario with skipped heartbeats.

**Comment by Boris-Plato** [comment]
btw since in your PR missInterval became heartbeatPeriod x3 with default value it is very close to our current fix with hardcoded heartbeatPeriod x2 =)
