### ISSUE TITLE
Channel.close does not appear to release resource

### ISSUE THREAD

**Issue by rajmaniar** [achilleasa/dart_amqp#11]
It looks like the `channelId` inserted into the `_ClientImpl._channel` map here: https://github.com/achilleasa/dart_amqp/blob/master/lib/src/client/impl/client_impl.dart#L268

Isn't removed when the channel is closed here:
https://github.com/achilleasa/dart_amqp/blob/master/lib/src/client/impl/channel_impl.dart#L200

For long running processes the instance of Client eventually hits the 65536 max and closes the client.

We could add `.then((_)=>_client._channels.remove(channelId));` but it's probably better to expose an api in `_ClientImpl` or bind an `onCancel` to the `_basicReturnStream` or something.

I'm happy to issue a PR with a fix, just let me know how you'd prefer to tackle it.

**Comment by achilleasa** [comment]
I think that your first suggestion `.then((_)=>_client._channels.remove(channelId));` is the way to go here. Feel free to submit a PR and I will merge it and push an update for the package. 

PS: I have updated the master branch to use travis-ci and codecov.io so all tests will run against the latest SDK version.

**Comment by rajmaniar** [comment]
Got it, thanks! PR is in.
