### ISSUE TITLE
Why isn't the latest merge (#117) on pub.dev?

### ISSUE THREAD

**Issue by boncossoftware** [achilleasa/dart_amqp#120]
Hi there! I was just wondering, if I see the code deployed on pub.dev (version 0.2.5, merge #95) I am not seeing the latest fixes (merge #117). How come? There are some fixes in there that I am really looking forward to but can't get via pub.dev. 🙏

**Comment by achilleasa** [comment]
Sorry for the delay. 

There are currently 2 outstanding open PRs. A new release will be published (within the next few days) once they land.

**Comment by boncossoftware** [comment]
Awesome. 👍 Thanks for the quick reply!

**Comment by achilleasa** [comment]
Version 0.3.0 has now been published.

**Comment by boncossoftware** [comment]
🙌 Awesome!
