### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by kendas** [achilleasa/dart_amqp#20]
Is there any plans of adding TLS support?

If so, is there a timeline?

**Comment by achilleasa** [comment]
Hi there. I have pushed a WIP [branch](https://github.com/achilleasa/dart_amqp/tree/add-support-for-tls-connections) that implements TLS support. 

To use that you need to create a `SecurityContext` with your TLS certs and attach it to a `ConnectionSettings` instance that you pass to the `Client` constructor. For example:

```dart
  String pathToCerts = "...";
  SecurityContext ctx = new SecurityContext()
  ..useCertificateChain(path + "client_certificate.pem")
  ..usePrivateKey(path + "client_key.pem")
  ..setClientAuthorities(path+"ca_certificate.pem");

  ConnectionSettings settings = new ConnectionSettings(tlsContext: ctx);
  Client client = new Client(settings: settings);
```

However, I haven't been able to get it to work with **self-signed** certificates (even though I explicitly provide the CA pem file to the context) without providing an accept-all callback (onBadCertificate) to `SecureSocket.connect` (it calls onBadCertificate for the CA pem).

Once I figure out a way to make this work properly I will open a PR.

**Comment by swampcoder** [comment]
Any chance this will be merged into a release soon?
