### ISSUE TITLE
heartbeat support

### ISSUE THREAD

**Issue by a14n** [achilleasa/dart_amqp#21]
In `dart_amqp-0.1.1` I can see a `TuningSettings.heartbeatPeriod` but this property doesn't seem to be used.

Is it supposed to work?

**Comment by achilleasa** [comment]
At the moment the client is not supporting heartbeats so this value is forced to 0 during the initial [handshake](https://github.com/achilleasa/dart_amqp/blob/64b803d3694f75729fe72f180e6d096aa8227db2/lib/src/client/impl/channel_impl.dart#L130) with the server.

**Comment by a14n** [comment]
Thanks for the info.
A workaround can be to have a unbound exchange into which regular publications are done. Any other idea?
