### ISSUE TITLE
Issues decoding strings with ØÆÅ 

### ISSUE THREAD

**Issue by HelgeSverre** [achilleasa/dart_amqp#31]
If i publish a message to a queue, where the message is a string containing Ø, Æ or Å, an error is thrown:

```FormatException: Bad UTF-8 encoding 0xf8 (at offset 21)```

Most likely caused by this line, not sure how to fix it thought, any thoughts on a workaround?

https://github.com/achilleasa/dart_amqp/blob/master/lib/src/protocol/frame/impl/decoded_message_impl.dart#L51

Code to replicate:

```dart
import 'dart:convert';

import 'package:dart_amqp/dart_amqp.dart';

void main() async {
  var client = await Client(
    settings: ConnectionSettings(
      host: "localhost",
      port: 5672,
      authProvider: PlainAuthenticator(
        "rabbitmq",
        "rabbitmq",
      ),
    ),
  );

  var queueName = "example_queue";

  // Setup a listener for a queue
  client
      .channel()
      .then((channel) => channel.queue(queueName))
      .then((Queue queue) => queue.consume())
      .then((Consumer consumer) {
    consumer.listen((AmqpMessage message) {
      // Both will fail with the following exception:
      // FormatException: Bad UTF-8 encoding 0xf8 (at offset 21)
      print(message.payloadAsString);
      print(message.payloadAsJson);
    });
  });

  // Publish a message to the queue
  client
      .channel()
      .then((channel) => channel.queue(queueName))
      .then((Queue queue) {
    // Publish the JSON string
    queue.publish("This string contains ø, æ or å");
  });
}

```

DartPad with example: 
https://dartpad.dartlang.org/94b3febd063256dd8b0445a698fb0c22

**Comment by HelgeSverre** [comment]
I have found a workaround:

If you encode the JSON as Base64 and then decode it back using message.payloadAsString, it will work.

**Comment by achilleasa** [comment]
Thanks for reporting this. This is clearly a bug in the way that _published_ messages are encoded. Let me investigate this further...

**Comment by achilleasa** [comment]
@HelgeSverre can you please verify that the proposed fix in #32 addresses the issues you are currently having with UTF8 values?

**Comment by HelgeSverre** [comment]
Can confirm that the following now works:

```dart
import 'dart:convert';

import 'package:dart_amqp/dart_amqp.dart';

void main() async {
  var client = await Client(
    settings: ConnectionSettings(
      host: "localhost",
      port: 5672,
      authProvider: PlainAuthenticator(
        "rabbitmq",
        "rabbitmq",
      ),
    ),
  );

  var queueName = "example_queue";

  // Setup a listener for a queue
  client
      .channel()
      .then((channel) => channel.queue(queueName))
      .then((Queue queue) => queue.consume())
      .then((Consumer consumer) {
    consumer.listen((AmqpMessage message) {
      // Both will fail with the following exception:
      // FormatException: Bad UTF-8 encoding 0xf8 (at offset 21)
      print(message.payloadAsString);
      print(message.payloadAsJson);
    });
  });

  // Publish a message to the queue
  client
      .channel()
      .then((channel) => channel.queue(queueName))
      .then((Queue queue) {
    // Publish the JSON string
    queue.publish({"url": "This string contains ø, æ or å"});
  });
}
```

However, publishing a plain string like this does still produce the same error:


```
queue.publish("This string contains ø, æ or å");
```

**Comment by achilleasa** [comment]
@HelgeSverre Can you double-check that you are not trying to process an un-acked message published using a previous version on the package? The linked PR includes [tests](https://github.com/achilleasa/dart_amqp/pull/32/commits/b6aeaf10d7aec7c02aedededa55107603bbe78f3) for both strings and json payloads

**Comment by HelgeSverre** [comment]
> @HelgeSverre Can you double-check that you are not trying to process an un-acked message published using a previous version on the package? The linked PR includes [tests](https://github.com/achilleasa/dart_amqp/pull/32/commits/b6aeaf10d7aec7c02aedededa55107603bbe78f3) for both strings and json payloads

Ahh silly me, that is exactly what i was doing :P 

Seems to work with both json and a plain string, excellent work. :+1:
