### ISSUE TITLE
How can i bind a queue with a exchange

### ISSUE THREAD

**Issue by ECat4** [achilleasa/dart_amqp#37]
As in the topic, i need to bind a queue to exchange.

**Comment by achilleasa** [comment]
To bind a private queue to an exchange you can follow the code from [this](https://github.com/achilleasa/dart_amqp/blob/master/example/routing/receive_logs_direct.dart#L30-L32) example. Exchanges also expose a [bindQueueConsumer](https://github.com/achilleasa/dart_amqp/blob/master/lib/src/client/exchange.dart#L56) method if you want to instead bind to a named queue.

**Comment by ECat4** [comment]
thank u , it works for me.





> To bind a private queue to an exchange you can follow the code from [this](https://github.com/achilleasa/dart_amqp/blob/master/example/routing/receive_logs_direct.dart#L30-L32) example. Exchanges also expose a [bindQueueConsumer](https://github.com/achilleasa/dart_amqp/blob/master/lib/src/client/exchange.dart#L56) method if you want to instead bind to a named queue.
