### ISSUE TITLE
After connection I get The null object does not have a getter 'msgClassId'. 

### ISSUE THREAD

**Issue by FaisalAbid** [achilleasa/dart_amqp#4]
Sometimes after connecting to my RabbitMQ instance I get the following error.

Jan 05 22:22:02 a41a608c3bea clever_bardeen:  The null object does not have a getter 'msgClassId'. 
Jan 05 22:22:02 a41a608c3bea clever_bardeen:  NoSuchMethodError: method not found: 'msgClassId' 
Jan 05 22:22:02 a41a608c3bea clever_bardeen:  Receiver: null 
Jan 05 22:22:02 a41a608c3bea clever_bardeen:  Arguments: [] 

Which ends up eventually throwing

 FatalException: Lost connection to the server.

Even though the server is fine.

**Comment by rajmaniar** [comment]
Try disabling the heartbeat in your server configs. I've had a very similar looking issue with RabbitMQ overriding the client connection settings.

**Comment by FaisalAbid** [comment]
Thanks I'll try that!

**Comment by FaisalAbid** [comment]
Arg, I'm using a cloud service to host rabbitmq and I don't think I can disable it, it's set to 120 seconds.

Hey @rajmaniar how would I go about implementing heartbeat in this driver? Would it just be a timer that sends specific data every 120 seconds or less?

**Comment by achilleasa** [comment]
Thanks for submitting a patch for that. 

I have merged it into master and published a new release. If there is enough interest I could look into implementing heartbeats.

**Comment by FaisalAbid** [comment]
Thanks @achilleasa . It would be awesome if you get around to implementing heartbeats. I think Dart needs one solid MQ solution and this is it!

Great work!
