### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by duhualong** [achilleasa/dart_amqp#40]
Code:
 ConnectionSettings settings = new ConnectionSettings(
        host: "192.168.50.83",
        port: 5672,
   virtualHost: '/',
        authProvider: new PlainAuthenticator("arx7", "arbalest"));
    Client client = new Client(settings: settings);

    Channel channel = await client.channel();
    Exchange exchange =
    await channel.exchange("luwak_topic", ExchangeType.TOPIC);
    Consumer consumer = await exchange.bindPrivateQueueConsumer(['#']);

        consumer.listen((message) {
      print(
          "[Exchange: ${message.exchangeName}] [${message.routingKey}] ${message.payloadAsString}");
    });

Question:
- inequivalent arg 'durable' for exchange 'luwak_topic' in vhost '/': received 'false' but current is 'true'

**Comment by achilleasa** [comment]
Looks like you are using a pre-existing exchange that was created with a durable flag and amqp expects that producers and consumers define shared resources using exactly the same flags. I believe that you can get it working by changing: 

```
await channel.exchange("luwak_topic", ExchangeType.TOPIC);
```

to:

```
await channel.exchange("luwak_topic", ExchangeType.TOPIC, durable: true);
```
