### ISSUE TITLE
Any plans on implementing AMQP 1.0?

### ISSUE THREAD

**Issue by 4F2E4A2E** [achilleasa/dart_amqp#41]
First of all, thank you so very much for this project.

Do you have any plans &/ capacity for implementing the AMQP 1.0? ActiveMQ Artemis (first release 2015) requires it.

**Comment by achilleasa** [comment]
The 1.0 version of the AMQP protocol has _significant_ differences from the 0.9.x version so unfortunately there are no plans to support it in this package. However, you might have better luck using [this](https://github.com/shamblett/amqp_client) client which seems to implement bindings for the apache QPID libraries.

**Comment by achilleasa** [comment]
Closing this; as mentioned above, there are no plans on supporting AMQP 1.0 as it uses a different protocol.
