### ISSUE TITLE
Not receiving messages when app is closed or terminated - using RabbitMq broker

### ISSUE THREAD

**Issue by servco313** [achilleasa/dart_amqp#44]
I am using RabbitMq as broker service. the issue is when my app is closed or terminated i am not receiving any message in queue.

**Comment by KiithNabaal** [comment]
In case anyone else comes across this, RabbitMQ nor its client libraries run in the background with Android or iOS. You either need to use Firebase or Apple Push Notification Service (or both) if you want your app to get messages even while closed. If you don't want to use these, I think there are ways to do it natively but it seems a little more complicated to do it that way.

Assuming you're using Flutter, there's also a library you can use to do push notifications.
