### ISSUE TITLE
Null Safety support

### ISSUE THREAD

**Issue by DrNik** [achilleasa/dart_amqp#47]
Hi,
is there any plan to support Sound Null Safety?

**Comment by achilleasa** [comment]
Not for the time being as this is a relatively new (2.12+ I believe) feature. It's definitely worth revisiting after a few more minor Dart releases are out.

**Comment by achilleasa** [comment]
I managed to allocate some time to make the required changes for enabling null-safety. The feature should be available in the upcoming 0.1.6 release.

**Comment by DrNik** [comment]
Nice news, thanks man.

**Comment by achilleasa** [comment]
I have bumped the minor version of the package as per the null-safety migration guidelines and published version 0.2.0 which enables null-safety support. Please let me know if you encounter any issues with it.
