### ISSUE TITLE
Not Support AMQP 1.0.0

### ISSUE THREAD

**Issue by tandacedric** [achilleasa/dart_amqp#67]
I got this error when i try to use ActiveMQ

E/flutter (29276): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FatalException: Could not negotiate a valid AMQP protocol version. Server supports AMQP 1.0.0

**Comment by achilleasa** [comment]
AMQP 1.x is not supported as there are significant changes in the protocol (see https://github.com/achilleasa/dart_amqp/issues/41 for more details).
