### ISSUE TITLE
The "qos" function does not work in queues of the "stream" type.

### ISSUE THREAD

**Issue by alexanderkind** [achilleasa/dart_amqp#68]
Hi!
RabbitMQ requires separate "qos" settings for each new consumer. (global = false)
https://www.rabbitmq.com/consumer-prefetch.html#overview

The abstract class "Channel" in the "qos" function is missing the "global" parameter.
This will fix everything.

Thanks!

**Comment by achilleasa** [comment]
FYI, the 0.2.2 release includes this change.
