### ISSUE TITLE
Any plans to implement heartbeats?

### ISSUE THREAD

**Issue by cbalmeida** [achilleasa/dart_amqp#71]
Are you guys having any plans to implement heartbeats? 

This is pretty necessary while we keep having lots of zombie connections on the server side!

**Comment by achilleasa** [comment]
Since this seems to be the most requested missing feature so far I will try to allocate some time over the next weeks to add support for heartbeats.

**Comment by achilleasa** [comment]
FYI, the 0.2.2 release includes this change.
